Console.WriteLine($"Rövid dátum: {DateTime.Now.ToShortDateString()}");
Console.WriteLine($"Hosszú dátum: {DateTime.Now.ToLongDateString()}");
Console.WriteLine($"Teljes dátum: {DateTime.Now:yyyy MMMM dd., dddd hh:mm:ss}");
Console.WriteLine($"Általános dátum, idő: {DateTime.Now}");
Console.WriteLine($"Rövid idő: {DateTime.Now.ToShortTimeString()}");
Console.WriteLine($"Hosszú idő: {DateTime.Now.ToLongTimeString()}");
Console.WriteLine($"Legkisebb dátum: {DateTime.MinValue}");
Console.WriteLine($"Legnagyobb dátum: {DateTime.MaxValue}");
Console.WriteLine($"A dátum számértéke: {DateTime.Now.Ticks}");
Console.WriteLine($"Aktuális dátum: {DateTime.Now.Date}");
Console.WriteLine($"Aktuális időpont: {DateTime.Now.TimeOfDay}");
Console.WriteLine($"Aktuális nap neve angolul: {DateTime.Now.DayOfWeek}");
Console.WriteLine($"Hányadik nap az évben: {DateTime.Now.DayOfYear}");
Console.WriteLine($"Hány napos a hónap: {DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)}");
Console.WriteLine($"A dátum éve: {DateTime.Now.Year}");
Console.WriteLine($"A hónap értéke: {DateTime.Now.Month}");
Console.WriteLine($"A dátum nap értéke: {DateTime.Now.Day}");
Console.WriteLine($"A dátum óra értéke: {DateTime.Now.Hour}");
Console.WriteLine($"A dátum perc értéke: {DateTime.Now.Minute}");
Console.WriteLine($"A dátum másodperc értéke: {DateTime.Now.Second}");
Console.WriteLine($"Tegnapi nap: {DateTime.Now.AddDays(-1).ToShortDateString()}");
Console.WriteLine($"Holnapi nap: {DateTime.Now.AddDays(1).ToShortDateString()}");
